# Generated by Django 4.0 on 2021-12-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='user_type',
            field=models.CharField(choices=[('junior', 'junior'), ('senior', 'senior')], default='junior', max_length=10),
        ),
    ]
